# Generated by Django 5.0.1 on 2024-02-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='news',
        ),
    ]
