# Generated by Django 5.0.1 on 2024-02-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='news_comments', to='base.review'),
        ),
    ]
