# Generated by Django 5.0.2 on 2024-02-21 17:25

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_news_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='places/', verbose_name='фото с мест на которых бывали')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок для фотографии')),
                ('photo', models.ImageField(upload_to='details/', verbose_name='фото для деталей')),
                ('description', models.TextField(verbose_name='Описание для фото')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата создания новости')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='homepage/widget')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Фейсбук')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Ссылка на Твиттер')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Инсту')),
                ('yotube', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ютуб')),
            ],
            options={
                'verbose_name': 'Виджет',
                'verbose_name_plural': 'Виджеты',
            },
        ),
    ]
