# Generated by Django 5.0.2 on 2024-02-21 18:25

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_blogpost_image_alter_blogpost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='places/', verbose_name='фото с мест на которых бывали'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(default=1, upload_to='details/', verbose_name='фото для деталей'),
            preserve_default=False,
        ),
    ]
