# Generated by Django 5.0.1 on 2024-02-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='photo',
            field=models.ImageField(default=1, upload_to='logo/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
